config/routes.rb
Datetrack::Application.routes.draw do

resources :users do
  resources :datees
end

get "/user-list" => "users#user_list"

resources :experiences do
  resources :surveys
end

get '/' => 'home#index'

get "/log-in" => 'sessions#new'
post "/log-in" => 'sessions#create', as: :log_in
get "/log-out" => 'sessions#destroy', as: :log_out

root to: "home#index"

post "/invite_user" => 'users#invite_user'
  

end

app/models/user.rb
class User < ActiveRecord::Base

has_many :datees

has_many :surveys
has_many :experiences

attr_accessor :password
before_save :encrypt_password

validates_confirmation_of :password
validates_presence_of :password, :on => :create
validates_presence_of :email
validates_uniqueness_of :email

has_attached_file :photo, :styles => { :small => "150x150>", :medium => "300x300" },
:url => "/system/:attachment/:id/:style/:basename.:extension",
:path => ":rails_root/public/system/:attachment/:id/:style/:basename.:extension"

validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

	def self.authenticate(email, password)
		user = User.where(email: email).first
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
end

app/controllers/users_controller.rb
require 'mandrill'  

class UsersController < ApplicationController
  def index
    if current_user.nil?
      redirect_to "/"
      flash[:alert] = "Please log-in or sign up before continuing..."
    end
  end

  def user_list
    @users = User.all
    render json: @users, status: 200
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thanks for joining Here's the thing..."
      session[:user_id] = @user.id
      redirect_to "/users"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user && @user.update_attributes(user_params)
      flash[:notice] = "Changes made - good to go!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Uh Oh - there was an issue with with your updates" 
      redirect_to :back
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user && @user.destroy
      flash[:notice] = "Your user has been deleted."
      redirect_to "/log-out"
    else
      flash[:alert] = "There was an issue deleting that user..."
      redirect_to "/users"
    end
  end

  def show
    @user = User.find(params[:id])
    #debugger
    #send_mail(@user.fname, @user.email, "your math")
    #debugger
    #respond_to do |format|
       # format.html # show.html.erb
        #format.xml { render :xml => @user }
    #end
  end

  def invite_user
    send_mail(params[:email], "Your friend has invited you to Here's the Thing!")
    redirect_to "/"
  end

# if params[:answer] == 0
#   message(params[:email], "Message is for this")
# elsif params[:answer] == 1

  # def send_mail(name, email, message)
  #   m = Mandrill::API.new
  #   #debugger
  #   message = {  
  #    :subject=> "Hello from the Mandrill API",  
  #    :from_name=> "Here's The Thing",  
  #    :text=>message,  
  #    :to=>[  
  #      {  
  #        :email=> email,  
  #        :name=> name,  
  #      }  
  #    ],  
  #    :html=>"<html>
  #         <h1>Hi, I'd like to invite you to checkout this awesome datetracking app.</h1>
  #         <a href='http://localhost:3000'>Link to Here's the Thing</a>
  #           </html>",  
  #    :from_email=>"sender@yourdomain.com"  
  #   }  
  #   sending = m.messages.send message  
  #   puts sending
  # end

private
def user_params
  params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :photo, :description)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit my profile...</h1>

<%=form_for @user,:url => user_path(@user), :html => { :multipart => true } do |f| %>
<%= f.file_field :photo %>
<br>
<%=f.label :fname %>
<%=f.text_field :fname %>
<%=f.label :lname %>
<%=f.text_field :lname %>
<br>
<%=f.label :email %>
<%=f.text_field :email %>
<br>
<%=f.label :password %>
<%=f.password_field :password %>
<br>
<%=f.label :password_confirmation %>
<%=f.password_field :password %>
<br>
<%=f.label :description %>
<%=f.text_field :description %>
<br>
<br>

<%=f.submit "Save Changes" %>
<% end %>

app/views/users/index.html.erb
<h2>We've all got our own things...</h2>
<!-- Initialize a new AngularJS app and associate it with a module named "instantSearch"-->
<div ng-app="instantSearch" ng-controller="InstantSearchController">

	<div class="bar">
		<!-- Create a binding between the searchString model and the text field -->
		<input type="text" ng-model="searchString" placeholder="Enter your search terms" />
	</div>

	<ul>
		<!-- Render a li element for every entry in the items array. Notice
			 the custom search filter "searchFor". It takes the value of the
			 searchString model as an argument.
		 -->
		<ul data-ng-repeat="i in items  | searchFor:searchString" >
			<img ng-src="system/photos/{{i.id}}/small/{{i.photo_file_name}}" />
			<br>
			<!-- <a href="{{i.url}}"><img ng-src="{{i.image}}" /></a> -->
			<a ng-href="users/{{i.id}}"/>
			<span data-ng-bind="i.fname" ></span>
			<span data-ng-bind="i.lname" ></span>
		</ul>
	</ul>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Here's the thing... join us!</p>
<br>
<br>
<%=form_for @user,:url => {:action => "create"}, :html => { :multipart => true } do |f| %>
<%=f.label :photo, "Upload your profile picture" %>
<%=f.file_field :photo %>
<br>
<%=f.label :fname, "First Name" %>
<%=f.text_field :fname %>
<%=f.label :lname, "Last Name" %>
<%=f.text_field :lname %>
<br>
<%=f.label :email %>
<%=f.text_field :email %>
<br>
<%=f.label :password %>
<%=f.password_field :password %>
<br>
<%=f.label :password_confirmation %>
<%=f.password_field :password %>
<br>
<%=f.submit "Sign Up!" %>
<% end %>

app/views/users/show.html.erb
<div class="experience-right">
	
</div>
<br>
<br>
<br>
<%= image_tag @user.photo.url (:medium)%>
<br>


<br>
<br>
	<% if @user.id != current_user.id  %>
		<p>Click me to set a date</p>
		<h1><%=link_to @user.fname + " " + @user.lname, new_experience_path(user_id: @user.id, fname: @user.fname) %> </h1>	
		<% else %>
		<% if @user.id == current_user.id %>
			<h1><%= @user.fname + " " +@user.lname %></h1>
			<%=link_to "Edit My Profile", edit_user_path(current_user.id) %>
			
			
		<% end %>
				
	<% end -%>
	<% if @user.id == current_user.id  %>
	<%= link_to "Delete My Account", user_path(current_user), method: :delete, confirm: "Are you sure you want to delete your account?" %>
	<% end -%>

<br>
<br>
<b>Here's my thing:</b>
<br>
<br>
<i><%= @user.description %></i>
<br>
<br>
<br>
<br>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>