config/routes.rb
Datetrack::Application.routes.draw do

resources :users do
  resources :datees
end

get "/user-list" => "users#user_list"

resources :experiences do
  resources :surveys
end

get '/' => 'home#index'

get "/log-in" => 'sessions#new'
post "/log-in" => 'sessions#create', as: :log_in
get "/log-out" => 'sessions#destroy', as: :log_out

root to: "home#index"

post "/invite_user" => 'users#invite_user'
  

end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :user
	has_one :survey
	
	#has_one :datee, through: :user
	belongs_to :datee, :class_name => 'User', :foreign_key => 'datee_id'

	
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    @experiences = Experience.where("user_id = ? OR datee_id = ?", current_user.id, current_user.id)
     
    @users = User.all


    @users = []
    @experiences.each do |experience|
      user = experience.user_id == current_user.id ? experience.datee : experience.user 
      
    
      @users.push user
    end
    @users.uniq!
    #debugger
  end

  def show
    @experience = Experience.find(params[:id])
  end

  def new
    @experience = Experience.new
  end

  def create
    
    @experience = Experience.new(experience_params)
    @user = User.where(id: params[:user_id].to_i).first
    
    if @user
      @experience.datee_id = @user.id
      @experience.fname = @user.fname
      @experience.user_id = current_user.id
      
      if @experience.date == nil
        @experience.date = Date.current
        
      end  
      #if a user is found, assign them to that experience, flash notice
      #to inform of success,
      #redirect.
      #@experience.user = current_user
      if @experience.save
        current_user.increment!(:number_of_experiences)
        flash[:notice] = "Your date has been saved."
        redirect_to experiences_path(@experience)
      else
        flash[:alert] = "Your date was unable to be saved."
        redirect_to :back
      end
    else
      flash[:alert] = "Sorry, there was no user found with that email."
      #redirect
    end 
  end

  def edit
    @experience = Experience.find(params[:id])

  end

  def update
    @experience = Experience.find(params[:id])
    if @experience && @experience.update_attributes(experience_params)
      flash[:notice] = "You experience has been updated!"
    else
      flash[:alert] = "There was an issue updating your experience."
    end
    redirect_to experience_path(@experience)
  end

  def destroy
    @experience = Experience.find(params[:id])
    if @experience.destroy
      flash[:notice] = "You date has been destroyed!"
      redirect_to "/experiences"
    else
      flash[:alert] = "There was an issue updating your date."
      redirect_to :back
    end
  end

  private

  def experience_params
    params.require(:experience).permit(:user_id, :fname, :date, :location, :description)
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/destroy.html.erb
<h1>Experiences#destroy</h1>
<p>Find me in app/views/experiences/destroy.html.erb</p>

app/views/experiences/edit.html.erb
<h1>Edit your date</h1>

<%=form_for [@experience] do |t| %>
	<%=label_tag(:user_email, "Who?") %>  
	<%=email_field_tag(:user_email) %>

	<br>
	<%=t.label(:date, "When?") %>  
	<%=t.date_field(:date) %>
	<br>
	<%=t.label(:location, "Where?") %>  
	<%=t.text_field(:location) %>
	<br>
	<%=t.label(:description, "Description:") %>  
	<%=t.text_area(:description) %>
	<br>
	<br>
	<%=t.submit :submit %>

<% end %>

app/views/experiences/index.html.erb
<h1>Your recent dates, <%= current_user.fname%>...</h1>

<div class="row">

	<div class="span8 experience-left">
		<% @experiences.each do |experience| %>
		<br>
			<strong>Survey:</strong> <%= link_to experience.fname,  new_experience_survey_path(experience.id, :datee_id => experience.datee_id, :fname =>
				experience.fname) %>

		<br>
			<strong>When:</strong> <%=link_to experience.date.strftime("%b, %d, %Y"), experience_path(experience) %>
		<br>
			<strong>Where:</strong> <%=experience.location %> 
		<br>
			<strong>Description:</strong> <%=experience.description %>
		<br>
			<strong>Created:</strong> <%= experience.created_at.strftime("%b, %d, %Y") %>
		<br>
		<br>
			<strong>Survey results:</strong> <%= link_to  experience.fname,  experience_survey_path(experience.id, :id => experience.datee_id ) %>
		<hr>
		<% end %>
		<br>
	</div>

	<div class="span4 experience-right">
		<h4>Invite Your Date</h4>

		<div>
			<%=form_tag "/invite_user" do |f| %>
				<%=label_tag :email, "Email" %>
				<%=text_field_tag :email %>
				<%=submit_tag :submit %>
			<% end %>
		</div>
		<% @users.each do |user| %>
			 
			<br>
			<%= image_tag user.photo.url (:small) rescue "" %>
			<h4><%= link_to user.fname, new_experience_path(user_id: user.id, fname: user.fname) %></h4>
			<br>
	
	<% end -%>

	</div>

</div>

app/views/experiences/new.html.erb
<h1>Save a New Date</h1>

<%=form_for [@experience] do |t| %>
	
	<%= hidden_field_tag(:user_id, params[:user_id]) %>

	<h2 class="date-fname">
	<%=label_tag(params[:fname]) %>  
	</h2>

	<br>
	<%=t.label(:date, "When?") %>  
	<%=t.date_field(:date) %>
	<br>
	<%=t.label(:location, "Where?") %>  
	<%=t.text_field(:location) %>
	<br>
	<%=t.label(:description, "Description:") %>  
	<%=t.text_area(:description) %>
	<br>
	<br>
	<%=t.submit :submit %>


<% end %>

app/views/experiences/show.html.erb
<h1>Your Experience</h1>

Who: <%=@experience.fname %> 
<br>
When: <%=@experience.date.strftime("%B #{@experience.date.day.ordinalize}, %Y") %>
<br>
Where: <%=@experience.location %> 
<br>
Description: <%=@experience.description %>
<br>
Created: <%=distance_of_time_in_words(Time.now, @experience.created_at) %>
<br>
<br>
<%= link_to "Edit this Experience", edit_experience_path %>
<br>
<%= link_to "Delete this Experience", experience_path(@experience), method: :delete, confirm: "Are you sure?" %>
<br>
<br>

<%= link_to "See all Experiences", experiences_path %>
<br>