config/routes.rb
Datetrack::Application.routes.draw do

resources :users do
  resources :datees
end

get "/user-list" => "users#user_list"

resources :experiences do
  resources :surveys
end

get '/' => 'home#index'

get "/log-in" => 'sessions#new'
post "/log-in" => 'sessions#create', as: :log_in
get "/log-out" => 'sessions#destroy', as: :log_out

root to: "home#index"

post "/invite_user" => 'users#invite_user'
  

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	

	has_many :users
	has_many :answers
	has_one :experience

	def is_similar?(current, datee)
		current_user_survey = Survey.where(:datee_id => datee, :user_id => current ).first
		 datee_survey = Survey.where(:datee_id => current, :user_id =>  datee ).first
		 #debugger
		if datee_survey && current_user_survey
			if datee_survey.answer == current_user_survey.answer

				return true
			end 
		end
	end	
end

app/controllers/surveys_controller.rb
require 'mandrill'  
class SurveysController < ApplicationController
	
   def index
		@user = User.find(params[:experience_id])
	end


	def show
		@survey = Survey.where(:datee_id => params[:id], :user_id => current_user.id ).first
		@experiences = Experience.where(:datee_id => params[:id], :user_id => current_user.id)
	end

	def new
		@survey = Survey.new
		@experience = Experience.find(params[:experience_id])

	end

	def create
		@survey = Survey.new(survey_params)
		#@survey.datee_id = params[:datee_id]
		@survey.user_id = current_user.id
		#debugger
		#@survey.answer = params[:answer].to_i
		if  @survey.save
		  if  @survey.is_similar?(@survey.user_id, @survey.datee_id)
			send_mail(current_user.fname, current_user.email, "You had a match!")
			flash[:notice] = "You have a match!"
		  end
			#flash[:notice] = "Your questionnaire has been saved."
			redirect_to experiences_path(@surveys)
		else
			@survey = Survey.where(params[:answer]).blank?
			flash[:alert] = "Your questionnaire was unable to be saved."
			redirect_to experiences_path(@surveys)
		end
	end

	private

	# def is_similar?(current, datee)
	# 	current_user_survey = Survey.where(:datee_id => datee, :user_id => current ).first
	# 	 datee_survey = Survey.where(:datee_id => current, :user_id =>  datee ).first
	# 	 #debugger
	# 	if datee_survey && current_user_survey
	# 		if datee_survey.answer == current_user_survey.answer

	# 			return true
	# 		end 
	# 	end
	# end	

	def survey_params
		params.permit(:answer, :user_id, :datee_id) 
	end

	## do not want to give others ability to edit/delete orig survey
	#def edit
	#	@survey = Survey.find(params[:id])

	#end

	#def update
	#	@survey = Survey.find(params[:id])
	#	if @survey && @survey.update_attributes(params[:survey])
	#		flash[:notice] = "You questionnaire has been updated!"
	#	else
	#		flash[:alert] = "There was an issue updating your questionnaire."
	#	end
	#	redirect_to user_survey_path(@survey.user, @survey)
	#end

	#def destroy
	#	@survey = Survey.find(params[:id])
	#	if @survey.destroy
	#		flash[:notice] = "You questionnaire has been deleted!"
	#		redirect_to user_survey_path(@survey.user)
	#	else
	#		flash[:alert] = "There was an issue deleting your questonnaire."
	#		redirect_to :back
	#	end
	#end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/create.html.erb
<h1>Surveys#create</h1>
<p>Find me in app/views/surveys/create.html.erb</p>

app/views/surveys/index.html.erb
<h1>Surveys#index</h1>
<p>Find me in app/views/surveys/index.html.erb</p>

app/views/surveys/new.html.erb
<h1>Surveys</h1>


<%=form_tag experience_surveys_path(@experience ), method: 'post' do %>


<p>With <%= @experience.fname  %>, I am looking for:</p>
<br>
<br> 
<%=radio_button_tag(:answer, 1) %>
<%=label_tag(:answer, "Friendship") %>
<br>
<%=radio_button_tag(:answer, 2) %>
<%=label_tag(:answer, "Hook-Up Only") %>
<br>
<%=radio_button_tag(:answer, 3) %>
<%=label_tag(:answer, "Casual Dating") %>
<br>
<%=radio_button_tag(:answer, 4) %>
<%=label_tag(:answer, "Exclusive Relationship") %>
<br>
<br>
<%= hidden_field_tag(:datee_id, @experience.datee_id) %>
<%=submit_tag "Submit" %>
<% end %>

app/views/surveys/show.html.erb
<h1>Surveys#show</h1>

<% @experiences.each do  |experience| %>
	Who: <%=experience.fname %> 
	<br>
	
	<br>
	Where: <%=experience.location %> 
	<br>
	Description: <%=experience.description %>
	<br>
	Created: <%=distance_of_time_in_words(Time.now, experience.created_at) %>
	<br>
	<br>
<% end -%>

<%= @survey.answer %>